### ISSUE TITLE
Create state locale file

### ISSUE THREAD

**Issue by rlgreen91** [EBWiki/EBWiki#1390]
Within `config/locales`, create a file `views/states/en.yml` that contains a list of states namespaced under states and en.  It should look a bit like this:

```
en:
  states:
    alaska: 'Alaska'
    arkansas:  'Arkansas'
```

The key for each state should be the same as those currently in the database.  The corresponding string value should be properly capitalized.  The key value pairs should be listed in alphabetical order.
