### ISSUE TITLE
Create ethnicity locale file

### ISSUE THREAD

**Issue by rlgreen91** [EBWiki/EBWiki#1391]
Within `config/locales`, create a file `views/ethnicities/en.yml` that contains a list of states namespaced under ethnicities and en.  It should look a bit like this:

```
en:
  ethnicities:
    asian: 'Asian'
    black: 'Black'
```

The key for each ethnicity should be the same as those currently in the database.  The corresponding string value should be properly capitalized.  The key value pairs should be listed in alphabetical order.
