### ISSUE TITLE
Create gender locale file

### ISSUE THREAD

**Issue by rlgreen91** [EBWiki/EBWiki#1392]
Within `config/locales`, create a file `views/genders/en.yml` that contains a list of states namespaced under genders and en.  It should look a bit like this:

```
en:
  genders:
    female: 'Female'
    male: 'Male'
```

The key for each gender should be the same as those currently in the database.  The corresponding string value should be properly capitalized.  The key value pairs should be listed in alphabetical order.
